Output pbr.gif
Set Padding 10
Set Theme "MaterialDarker"
Set FontSize 14
Set TypingSpeed 75ms
Set Width 1000
Set Height 390

Sleep 1s
Type@23ms "You can move pbr binary into your $PATH"
Sleep 3s
Backspace@1ms 40
Sleep 500ms

Type@1ms "clear"
Enter
Sleep 1s

Type@7ms "./pbr 3 wss://eth-mainnet.g.alchemy.com/v2/ wss://mainnet.infura.io/ws/v3/ wss://failing.rpc.endpoint.wtf/rpc/eth"
Tab
Enter
Sleep 50s